# Word Embedding 

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### initialize my sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
#vocbulary size 
voc_size = 10000

## One Hot Representation

In [ ]:
onehot_rep = [one_hot(words,voc_size) for words in sent]
onehot_rep

[[8851, 4311, 505, 3271],
 [8851, 4311, 505, 3939],
 [8851, 5068, 505, 7776],
 [1525, 7539, 7382, 660, 1626],
 [1525, 7539, 7382, 660, 6845],
 [9815, 8851, 6552, 505, 5404],
 [6298, 9553, 4294, 660]]

##Word Embedding Reprsentation

In [ ]:
import numpy as np
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
sent_length = 8
embedded_docs = pad_sequences(onehot_rep, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 8851 4311  505 3271]
 [   0    0    0    0 8851 4311  505 3939]
 [   0    0    0    0 8851 5068  505 7776]
 [   0    0    0 1525 7539 7382  660 1626]
 [   0    0    0 1525 7539 7382  660 6845]
 [   0    0    0 9815 8851 6552  505 5404]
 [   0    0    0    0 6298 9553 4294  660]]


In [ ]:
dim = 10

In [ ]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length = sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))

[[[-0.03661398  0.00686298  0.01628572  0.02655712 -0.04657711
   -0.03635935  0.03217578  0.01671802  0.02080388 -0.04798254]
  [-0.03661398  0.00686298  0.01628572  0.02655712 -0.04657711
   -0.03635935  0.03217578  0.01671802  0.02080388 -0.04798254]
  [-0.03661398  0.00686298  0.01628572  0.02655712 -0.04657711
   -0.03635935  0.03217578  0.01671802  0.02080388 -0.04798254]
  [-0.03661398  0.00686298  0.01628572  0.02655712 -0.04657711
   -0.03635935  0.03217578  0.01671802  0.02080388 -0.04798254]
  [ 0.00875743 -0.04473228  0.01955153 -0.01829612  0.04301966
   -0.0411681  -0.02380047  0.01861936 -0.04170882  0.01201297]
  [-0.04702063  0.00027348  0.02062598  0.03226246  0.01345764
    0.03195878 -0.04724037 -0.00850201  0.02530203 -0.04890488]
  [ 0.00968776 -0.03923895  0.02270445 -0.0098505  -0.01454623
   -0.04936901  0.00545195 -0.01988031  0.02480635  0.03947194]
  [-0.03160604  0.00726442 -0.02187577  0.0140109  -0.04926393
   -0.01479266  0.0009612   0.02727995 -0.015574

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 8851, 4311,  505, 3271], dtype=int32)

In [ ]:
print(model.predict(embedded_docs[0]))

[[[-0.03661398  0.00686298  0.01628572  0.02655712 -0.04657711
   -0.03635935  0.03217578  0.01671802  0.02080388 -0.04798254]]

 [[-0.03661398  0.00686298  0.01628572  0.02655712 -0.04657711
   -0.03635935  0.03217578  0.01671802  0.02080388 -0.04798254]]

 [[-0.03661398  0.00686298  0.01628572  0.02655712 -0.04657711
   -0.03635935  0.03217578  0.01671802  0.02080388 -0.04798254]]

 [[-0.03661398  0.00686298  0.01628572  0.02655712 -0.04657711
   -0.03635935  0.03217578  0.01671802  0.02080388 -0.04798254]]

 [[ 0.00875743 -0.04473228  0.01955153 -0.01829612  0.04301966
   -0.0411681  -0.02380047  0.01861936 -0.04170882  0.01201297]]

 [[-0.04702063  0.00027348  0.02062598  0.03226246  0.01345764
    0.03195878 -0.04724037 -0.00850201  0.02530203 -0.04890488]]

 [[ 0.00968776 -0.03923895  0.02270445 -0.0098505  -0.01454623
   -0.04936901  0.00545195 -0.01988031  0.02480635  0.03947194]]

 [[-0.03160604  0.00726442 -0.02187577  0.0140109  -0.04926393
   -0.01479266  0.0009612   0.0272